### ISSUE TITLE
Move this repository to the IOOS organization and/or increase the maintainers here

### ISSUE THREAD

**Issue by ocefpaf** [axiom-data-science/docker-erddap#41]
We started this discussion via email a while back but we never decided on a strategy to implement this.

The options we have discussed so far are:

1. increase the people with admin access to this repository
2. move this repository to the IOOS org and increase the number of people with write access to it
3. move it to the ERDDAP repostory

I'm inclined towards option 2 b/c that sends a message that this image is 'blessed' by IOOS and we have easier access to it. While 3 is tempting I'm afraid that the bus factor would still be low with that option.

Pinging @abkfenris, @mwengren, @MathewBiddle, and @kwilcox.

**Comment by MathewBiddle** [comment]
xref to ERDDAP Google Group thread: https://groups.google.com/g/erddap/c/HJfeOyVE-88/m/HZB0wzsHAgAJ

**Comment by kwilcox** [comment]
I prefer option 3 so an "official" docker image is maintained and produced with each iteration of ERDDAP. Reduces confusion and increases trust. That being said... option 2 is the best option for us to explore in the short term to clear up any outstanding issues.

**Comment by abkfenris** [comment]
I also prefer that we continue to work down the path towards option 3, but that 2 is the best option for near term.

**Comment by abkfenris** [comment]
What do we need for us to move this repo to the IOOS org?

- Axiom
  - Add an open source license (does IOOS have a prefered license? A quick look shows a mix of MIT/BSD/Apache)
  - Add an [IOOS admin](https://github.com/orgs/ioos/people?query=role%3Aowner) as a repo admin
  - Mark Docker Hub repo as deprecated after a new repo is setup.
- IOOS Org Admin
  - [Transfer repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to IOOS.
  - Create an @ioos/docker-erddap-maintainers (or something else reasonably named) with maintain access to the repo, and figure out who will be on it
- New maintainers
  - Setup up Docker Hub repo to push images too (or maybe we should just host images right on Github? That might mean less personal access tokens getting left around everywhere...)
  - Push latest and 2.18 images to repo, and update automation.

Anything else that folks can think of?

**Comment by kwilcox** [comment]
Now that all of the issues are cleared up and new versions are pushed I'd prefer to increase the maintainers here until we can figure out a plan for an "official" ERDDAP image.

**Comment by MathewBiddle** [comment]
@kwilcox this might be a good code sprint topic https://github.com/ioos/ioos-code-sprint/blob/main/2022/track-list.md

**Comment by abkfenris** [comment]
Since Bob was open to it, and I needed something to rage code, I started [a PR on the ERDDAP repo](https://github.com/BobSimons/erddap/pull/79) to build Docker images. It still needs a good bit of work, and I could use some help from folks who know Java better than I do.

Here is where I'm currently at: https://github.com/BobSimons/erddap/issues/60#issuecomment-1169199421

**Comment by BobSimons** [comment]
After some private discussions, I think I don't like your proposed system to use GitHub Actions to test ERDDAP, generate erddap.war, then make the Docker version of ERDDAP. The main problems are that:
* It's very hard to set up and maintain a full ERDDAP test environment. ERDDAP works with live, changing datasets, so it is a complex testing environment.
* Not all tests pass. There are known problems (e.g., bugs in netcdf-java reported to Unidate but unsolved, and test datasets that are now gone).
* The release process involves me testing erddap.war on a public server before releasing it to others. It's better to catch bugs here than after releasing ERDDAP to others.
* I don't want to turn over control of making erddap.war. That leaves me responsible for other people's work. That's trouble. And it necessitates a lot of interaction so that all changes to the script that makes erddap.war are properly committed and tested.  That is unnecessary and error prone.

I think it is far better for you to make a (semi) automated system that: 
* Is triggered by someone running a script, not GitHub Actions.
* Uses my erddap.war when I make it available.
* Has my products in my GitHub repository, and your products in your repository. That way we each have responsibility for what is in our own repository. The line of demarcation is clear. And ERDDAP-related issues will be handled in my repository and Docker-related issues will be handled in your repository.

That avoids tons of trouble and unnecessary interactions. It is a clear line of separation of responsibilities.
That approach is easier for you -- you can develop and test your script any time by running it against the current official erddap.war.
And my release notes will point to your GitHub repository as the place to go for the Docker version.

**Comment by ocefpaf** [comment]
We are going [with option 1 for now](https://github.com/axiom-data-science/docker-erddap/issues/41#issue-1148282057). Thanks all!
